### ISSUE TITLE
Bug in generate_text function

### ISSUE THREAD

**Issue by TedSIWEILIU** [Suro-One/Hyena-Hierarchy#1]
Hi, thanks for providing the code for Hyena. However, when I tried to run the code, it triggered the following error:
`line 41, in forward
    x = x.transpose(1, 2).contiguous().view(-1, self.depth * self.positional_dim)
RuntimeError: shape '[-1, 9]' is invalid for input of size 213`

I think this is due to a bug in the def generate_text(). Do you have any idea how to fix this?

**Comment by Suro-One** [comment]
Resolved
